Small changes to Document Explorer table
jataware/dojo pull request #84
Opened 2023-05-23 16:00 UTC by adamgilg

This updates the following in the Document Explorer table/grid: 

- Removes the Description column from the table and adds description to each document's dialog 
- Adds uploaded_at as a column
- Renames uploaded_at and creation_date to `Date Created` and `Date Uploaded`

2023-05-23 16:01 UTC, mattprintz approved these changes

2023-05-24 14:34 UTC, ccjoel requested changes
I ran this and realized that @adamgilg doesn't have access to proper uploaded documents (his macbook won't really run the text extraction/embedding within a docker container). Looks like we need to format the values for `Date Uploaded` when displaying them.

Take a look:

![Screenshot from 2023-05-24 10-32-03](https://github.com/jataware/dojo-stack/assets/1967061/bd8fe87d-5119-4660-86eb-859c18457f60)

The rest is fantastically outstanding.

ps. Maybe I need to share a backup of my es docs//paragraphs index with @adamgilg. We can talk more about something like that later.

2023-05-24 22:06 UTC, adamgilg commented
Ahh good catch. I'll ping you tomorrow about this @ccjoel

2023-05-30 20:46 UTC, adamgilg commented
Fixed it with the same date formatting as Date Created.

2023-05-31 19:46 UTC, ccjoel approved these changes
Awesome!

2023-05-31 19:46 UTC, merged